version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/app/deploys/last
permissions:
  - object: /var/www/app
    owner: app
hooks:
  AfterInstall:
    - location: deploy/after_install
      timeout: 300
      runas: app
  ApplicationStart:
    - location: deploy/restart
      timeout: 300
      runas: app

