#!/bin/sh

set -e

CURRENT=/var/www/app/current
LAST=/var/www/app/deploys/last
DEST=/var/www/app/deploys/${DEPLOYMENT_ID}

mv $LAST $DEST
cd $DEST
bundle install --deployment --without development test
bundle exec rake assets:precompile db:migrate RAILS_ENV=production
ln -sfn $DEST $CURRENT
echo $DEPLOYMENT_ID > $DEST/config/deployment_id
