#!/bin/sh

set -e

CURRENT=/var/www/myapp/current
LAST=/var/www/myapp/deploys/last
DEST=/var/www/myapp/deploys/${DEPLOYMENT_ID}

echo "mv $LAST $DEST" > /tmp/log

mv $LAST $DEST
cd $DEST
bundle install --deployment --without development test
bundle exec rake assets:precompile db:migrate RAILS_ENV=production
ln -sfn $DEST $CURRENT
